### ISSUE TITLE
(régression) La section "anomalies présentes sur toutes les pages" est vide

### ISSUE THREAD

**Issue by yaaax** [DISIC/frago#11]
... même s'il existe effectivement des anomalies présentes sur toutes les pages.

**Comment by bertrandkeller** [comment]
Le contenu des cellules doit être exactement identique pour un critère en particulier.

Est-ce que ce bug réel, ou est-ce une différence de saisie ?

**Comment by yaaax** [comment]
Cette régression semble corrigée depuis. On peut fermer ;)
