### ISSUE TITLE
Lien en double : "Accéder au rapport"

### ISSUE THREAD

**Issue by yaaax** [DISIC/frago#12]
<img width="846" alt="acceder-en-double" src="https://user-images.githubusercontent.com/11678850/139811639-c5b1cea2-6c10-49d8-8192-84b74cebc8bf.png">

Bug reproduit ici :
- https://design.numerique.gouv.fr/audits/dila/audits/1879/
- https://github.com/DISIC/dsn-audits-dila

**Comment by bertrandkeller** [comment]
C'est corrigé.
