### ISSUE TITLE
Ajouter le taux moyen de conformité

### ISSUE THREAD

**Issue by yaaax** [DISIC/frago#13]
Cf. [Taux de conformité à la norme](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#taux-de-conformit%C3%A9-%C3%A0-la-norme)

> Ce taux peut indiquer **le pourcentage de critères respectés** *ou* **le niveau de conformité moyen** du service en ligne.

**Comment by yaaax** [comment]
@bertrandkeller on peut clore cette Issue ?

**Comment by bertrandkeller** [comment]
Oui, c'est fait
