### ISSUE TITLE
Tableaux du rapport "quality"

### ISSUE THREAD

**Issue by sdrouvroy** [DISIC/frago#18]
J'essaie de comprendre comment fonctionnent les tableaux. 

- A quoi correspond réellement la colonne 'Type' ? et comment on définit le "titre" de la ligne ? 
- Est-ce que ça correspond à un élément précis de la page ou bien autre chose ?  
- Comment est-ce que tu définis les "lots" ? 

Merci :)

**Comment by bertrandkeller** [comment]
Bonjour,

1. Type, c'est sensé être une attribut pour répartir le travail entre métier : code, visuel, texte (mais c'est pas facile à remplir, je devrais le supprimer, je sais pas si c'est pertinent).
2. Le titre c'est le nom de l'erreur, `name`.
3. Un lot, tu ajoutes `delivery: lot 1 - Langue` à ton erreur - tu mets ce que tu veux comme nom et tout ceux qui ont le même nom sont regroupés (affichage par orde alphabétique). Théoriquement ça peut correspondre à des sprints pour étaler les corrections. Ça dot permettre de répondre à la question : on ne sait pas par quoi commencer.

**Comment by sdrouvroy** [comment]
Peut être définir une liste de "type" pour qu'on puisse se l'approprier davantage ? 
Je pense que cette colonne peut avoir sa place mais il faut qu'on puisse se l'approprier. 

Ok pour le type et le lot. Je commence à y voir un sens :-)

**Comment by bertrandkeller** [comment]
Je regarde, mais je trouve quand m^me que le type est un peu chiant à remplir quand tu fais un copier/coller. Ça apporte peut de plus value, mais on peut le garder.
