### ISSUE TITLE
La vue "Conformité détaillée" ne tient pas compte des critères non applicables (na)

### ISSUE THREAD

**Issue by yaaax** [DISIC/frago#2]
<img width="954" alt="global-vs-detaille" src="https://user-images.githubusercontent.com/11678850/132141222-2ba3420a-825f-40d9-8d14-40d4145de41b.png">

**Comment by bertrandkeller** [comment]
Oui à quel niveau ? 
C'est normal dans le calcul, on ne prend pas en compte les na. Je ne vois pas pourquoi les prendre en compte.

**Comment by yaaax** [comment]
Est-ce qu'on ne pourrait pas mettre que les non-conformités ? Parce-que finalement ce n'est que cette information qui est importante sur ce graphe.
Pas très important, il faudrait demander à un designer ;)
