### ISSUE TITLE
Erreurs en local

### ISSUE THREAD

**Issue by sdrouvroy** [DISIC/frago#20]
J'ai cette erreur en local, comment je peux faire pour ne plus l'avoir. c'est perturbant... 
![Capture d’écran 2022-02-18 à 10 41 17](https://user-images.githubusercontent.com/97090203/154662905-e7675a4d-bf24-41fa-9938-9058c638baf0.png)

**Comment by sdrouvroy** [comment]
Hello,
Ca reste présent quand même ... malgré la commande que tu m'as conseillée

**Comment by bertrandkeller** [comment]
J'ai passé le caractère dans la CSS. Ça va disparaître bientôt.

**Comment by bertrandkeller** [comment]
Est que l'erreur est toujours là ?
