### ISSUE TITLE
Audit "Qualité"  à convertir en "recommandations"

### ISSUE THREAD

**Issue by sdrouvroy** [DISIC/frago#21]
Est-ce qu'il y aurait moyen de changer le terme de "qualité" quand on utilise cette partie pour faire remonter les différentes erreurs d'accessibilité par type de lot ? (L'utilisateur final ne connait pas forcément la qualité ou inversement et ça peut être déroutant aussi ... )

**Comment by bertrandkeller** [comment]
recommendation ? en anglais 
recommandation  ? en français

**Comment by sdrouvroy** [comment]
Pour les préconisations de corrections oui :-)

**Comment by bertrandkeller** [comment]
Je vais bosser sur le sujet. 

On peut inclure les audits accessibilité dans une répertoire : `accessibility` ou `rgaa`. Au choix. 
Un peu de code en plus mais je pense que le code est présent pour avoir : `quality` ou `recommendation`

Je traiterai ça bientôt.

**Comment by bertrandkeller** [comment]
En théorie la pull request doit permettre "recommendation" ou "recommendations".
