### ISSUE TITLE
Modifier la phrase "pour atteindre 75%"

### ISSUE THREAD

**Issue by sdrouvroy** [DISIC/frago#33]
Il faut enlever cette phrase qui n'est pas exacte en "objectif à atteindre", le RGAA demande à ce que ce soit totalement conforme. Soit on met 100% soit on met rien du tout … mais pas 75% ;-)

**Comment by bertrandkeller** [comment]
Cette phrase n'existe plus.
https://github.com/DISIC/frago/commit/ab2713ee6413a5f4348e2a6df2ab0949e93fff96
